# Generated by Django 2.2 on 2020-06-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pontoturistico_avaliacoes'),
        ('atracoes', '0002_auto_20200628_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atracoes',
            new_name='Atracao',
        ),
    ]
